package andresgoncalves.quiz1;

import java.awt.CardLayout;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Andres
 */
public class App extends javax.swing.JFrame {
    
    private List<Series> series = new List<Series>();

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
    }
    
    public void loadFile(File file) {
        try {
            series = DataLoader.load(file);
            cataloguePanel.setSeries(series);
            showCard("CatalogueCard");
        } catch (IOException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "No se pudo cargar el archivo", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void showCard(String name) {
        ((CardLayout) mainPanel.getLayout()).show(mainPanel, name);
    }

    public List<Series> getSeries() {
        return series;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        fileLoaderPanel = new andresgoncalves.quiz1.FileLoaderPanel();
        cataloguePanel = new andresgoncalves.quiz1.CataloguePanel();
        buttonPanel = new javax.swing.JPanel();
        fileButton = new javax.swing.JButton();
        catalogueButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        mainPanel.setLayout(new java.awt.CardLayout());
        mainPanel.add(fileLoaderPanel, "FileLoaderCard");
        mainPanel.add(cataloguePanel, "CatalogueCard");

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        buttonPanel.setLayout(new java.awt.GridBagLayout());

        fileButton.setText("Archivo");
        fileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        buttonPanel.add(fileButton, gridBagConstraints);

        catalogueButton.setText("Catálogo");
        catalogueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catalogueButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        buttonPanel.add(catalogueButton, gridBagConstraints);

        searchButton.setText("Buscar");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        buttonPanel.add(searchButton, gridBagConstraints);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileButtonActionPerformed
        showCard("FileLoaderCard");
    }//GEN-LAST:event_fileButtonActionPerformed

    private void catalogueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catalogueButtonActionPerformed
        showCard("CatalogueCard");
    }//GEN-LAST:event_catalogueButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        showCard("SearchCard");
    }//GEN-LAST:event_searchButtonActionPerformed

    private static App instance;
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());         
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            instance = new App();
            instance.setVisible(true);
        });
    }

    public static App getInstance() {
        return instance;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton catalogueButton;
    private andresgoncalves.quiz1.CataloguePanel cataloguePanel;
    private javax.swing.JButton fileButton;
    private andresgoncalves.quiz1.FileLoaderPanel fileLoaderPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
}
