package andresgoncalves.quiz1;

import javax.swing.JOptionPane;

/**
 *
 * @author Andres
 */
public class EpisodeSearchPanel extends javax.swing.JPanel {
    
    private Series series;
    private Episode selectedEpisode;

    /**
     * Creates new form SearchPanel
     */
    public EpisodeSearchPanel() {
        initComponents();
        contentPanel.setVisible(false);
    }

    public Episode findEpisode(String search) {
        if(search.isBlank()) {
            return null;
        }
        search = search.toLowerCase();
        for(Node<Episode> node = series.getEpisodes().getFirst(); node != null; node = node.getNext()) {
            if(node.getValue().getName().toLowerCase().contains(search)) {
                return node.getValue();
            }
        }
        return null;
    }
    
    public void loadSeries() {
        if(selectedEpisode == null) {
            JOptionPane.showMessageDialog(this, "Capítulo no encontrado", "Error", JOptionPane.WARNING_MESSAGE);
            contentPanel.setVisible(false);
        }
        else {
            titleLabel.setText(selectedEpisode.getName());
            sinopsisTextArea.setText(selectedEpisode.getSinopsis());
            contentPanel.setVisible(true);
        }
    }

    public void setSeries(Series series) {
        this.series = series;
        selectedEpisode = null;
    }

    public Episode getSelectedEpisode() {
        return selectedEpisode;
    }

    public void setSelectedEpisode(Episode selectedEpisode) {
        this.selectedEpisode = selectedEpisode;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        searchBarPanel = new javax.swing.JPanel();
        searchTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        sinopsisLabel = new javax.swing.JLabel();
        sinopsisScrollPane = new javax.swing.JScrollPane();
        sinopsisTextArea = new javax.swing.JTextArea();
        buttonPanel = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setLayout(new java.awt.BorderLayout());

        searchBarPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        searchBarPanel.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        searchBarPanel.add(searchTextField, gridBagConstraints);

        searchButton.setText("Buscar capítulo");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        searchBarPanel.add(searchButton, gridBagConstraints);

        add(searchBarPanel, java.awt.BorderLayout.NORTH);

        contentPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        contentPanel.setLayout(new java.awt.GridBagLayout());

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titleLabel.setText("Capítulo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        contentPanel.add(titleLabel, gridBagConstraints);

        sinopsisLabel.setText("Sinopsis");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 10, 0);
        contentPanel.add(sinopsisLabel, gridBagConstraints);

        sinopsisTextArea.setEditable(false);
        sinopsisTextArea.setColumns(20);
        sinopsisTextArea.setLineWrap(true);
        sinopsisTextArea.setRows(5);
        sinopsisScrollPane.setViewportView(sinopsisTextArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        contentPanel.add(sinopsisScrollPane, gridBagConstraints);

        add(contentPanel, java.awt.BorderLayout.CENTER);

        buttonPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        buttonPanel.setLayout(new java.awt.GridBagLayout());

        backButton.setText("Volver");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        buttonPanel.add(backButton, gridBagConstraints);

        add(buttonPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        selectedEpisode = findEpisode(searchTextField.getText());
        loadSeries();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        App.getInstance().showSeriesSearchCard();
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel searchBarPanel;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JLabel sinopsisLabel;
    private javax.swing.JScrollPane sinopsisScrollPane;
    private javax.swing.JTextArea sinopsisTextArea;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
